name: VMCombatLogger
version: 1.2.5
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: VMPE Development Team
main: Lambo\CombatLogger\Main
description: One of the best working Combat Loggers plugin running the latest PMMP-Build.
